### ISSUE TITLE
World list scrolls on top of tabs in sidebar

### ISSUE THREAD

**Issue by robertlong** [matrix-org/thirdroom#100]
**Describe the bug**
When using a short window (or when you have your devtools open), the world list scrolls on top of the tabs in the sidebar

**To Reproduce**
1. Have a couple worlds in your sidebar
2. Shrink the browser window vertically
3. Scroll to the bottom of your room list and to the friends list at the bottom of the sidebar
4. Observe the world avatar on top of the tabs

**Expected behavior**
It should always scroll behind the tabs

**Screenshots**
<img width="415" alt="Screen Shot 2022-07-05 at 3 52 20 PM" src="https://user-images.githubusercontent.com/1753624/177430359-156e6a61-fe5f-48ad-8000-5bb956a197bd.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 103

**Comment by ajbura** [comment]
This has been fixed in [PR](https://github.com/matrix-org/thirdroom/pull/107).

**Comment by robertlong** [comment]
Yup, thanks Ajay!
