### ISSUE TITLE
Firefox fails to load complex scenes with an out of memory error

### ISSUE THREAD

**Issue by robertlong** [matrix-org/thirdroom#101]
This is a known issue with how Firefox allocates SharedArrayBuffers. There's an artificial upper limit of around 1000 that is not present in Chromium based browsers. It looks like it's now being worked on and a fix will hopefully be out shortly.

Bugzilla issues:
https://bugzilla.mozilla.org/show_bug.cgi?id=1689948
https://bugzilla.mozilla.org/show_bug.cgi?id=1778077

**Comment by robertlong** [comment]
The fix is now merged into the FF 104 branch and is working in the latest FF Nightly release.

**Comment by NateTheGreatt** [comment]
104 released!
