### ISSUE TITLE
Fail to join room without a microphone connected

### ISSUE THREAD

**Issue by robertlong** [matrix-org/thirdroom#111]
**Describe the bug**
A user reported an issue where they tried to join the room without a microphone connection. They received the following error:

`Uncaught (in promise) DOMException: Requested device not found`

With a microphone connected the user stated that they were able to enter the room.

**To Reproduce**
TODO

**Expected behavior**
The user should enter the room or an error should be displayed if it still fails

**Screenshots**
N/A

**Desktop (please complete the following information):**
Chrome via flatpak on Linux

**Additional context**
None

**Comment by eshattow** [comment]
Confirming with no microphone attached Third Room does not load in Chrome on Debian GNU/Linux. Plug in a webcam and set Chrome to use that microphone, and then Third Room loads normally.
