### ISSUE TITLE
Login / Registration via OpenID Connect

### ISSUE THREAD

**Issue by robertlong** [matrix-org/thirdroom#121]
Work has been underway for some time on OpenID Connect for auth in Matrix. We should utilize OpenID Connect in Third Room instead of building out yet another Matrix.org managed auth/user registration project.

**Comment by davidak** [comment]
You are probably aware of it, but Matrix is working on making OpenID Connect the standard auth, so i guess you should just wait for that and use it instead of duplicating the effort.

https://matrix.org/blog/2022/08/10/areweoidcyet-com-matrix-and-open-id-connect
