### ISSUE TITLE
Social Management Features

### ISSUE THREAD

**Issue by robertlong** [matrix-org/thirdroom#146]
To Do:
- [x] Cursor that changes state when you look at a user
- [x] Raycaster which allows you to detect when you're looking at a user
- [x] Display nametag when you look over a user (or maybe a shapecast so that it's a bit more broad of a target)
- [x] Display all nametags in frustum when you toggle a hotkey
- [x] When you click a user (or maybe right click) you bring up the member list with that member focused.
- [x] Member list can also be brought up with a hotkey
- [x] Member list needs a mute / block button.
- [x] Mute state should probably just be stored in memory
- [ ] Block I think is equivalent to Matrix's ignore? We just need to figure out what this means for networking state.

Related to #145

**Comment by NateTheGreatt** [comment]
#151 added the following:

- [x] Display nametag when you look over a user (or maybe a shapecast so that it's a bit more broad of a target)
- [x] Display all nametags in frustum when you toggle a hotkey

**Comment by NateTheGreatt** [comment]
#154 adding the following:
- [ ] Display nametag when you look over a user (or maybe a shapecast so that it's a bit more broad of a target)
- [ ] Display all nametags in frustum when you toggle a hotkey

**Comment by NateTheGreatt** [comment]
#160 adding:
- [ ] When you click a user (or maybe right click) you bring up the member list with that member focused.
- [ ] Member list can also be brought up with a hotkey
- [ ] Member list needs a mute / block button.
- [ ] Mute state should probably just be stored in memory
- [ ] Block I think is equivalent to Matrix's ignore? We just need to figure out what this means for networking state.

**Comment by NateTheGreatt** [comment]
#175 adding:
- [ ] Display all nametags in frustum when you toggle a hotkey
