### ISSUE TITLE
Colliders don't always remove when changing scenes

### ISSUE THREAD

**Issue by robertlong** [matrix-org/thirdroom#147]
**Describe the bug**
When swapping scenes we sometimes see colliders stick around even though their visual component is removed.

**To Reproduce**
1. Go to the UK City world and enter the world
2. In the same session join the City world and enter the world
3. Observe that you can collide with the UK City scene colliders

**Expected behavior**
The engine should always remove the colliders when exiting a scene.

**Screenshots**
Don't have any on hand.

**Desktop (please complete the following information):**
All browsers / platforms 

**Additional context**
This seems to be intermittent so you may need to test a couple times to reproduce.

**Comment by NateTheGreatt** [comment]
did some investigation here. it appears as though not all child entities with rigidbodies are hitting the physics exit query. this points to removals during scene unloading potentially not traversing to all relevant children.

**Comment by NateTheGreatt** [comment]
this may be due to entity ID recycling
