### ISSUE TITLE
Allow for room joins without first providing microphone permission

### ISSUE THREAD

**Issue by davidak** [matrix-org/thirdroom#163]
**Describe the bug**

I was curious enough to log in, but when it asks for microphone permission, i'm too scared to proceed.

**To Reproduce**
1. Go to https://thirdroom.io/world/#thirdroom-public:matrix.org
2. Click on 'Enter World'
3. Site asks for permission to use microphone
4. Being scared

**Expected behavior**

To be an inclusive and accessible social space, the software should empower users to participate in a safe and non-overwhelming way, even when they have social anxiety or other social problems.

An option to join muted, like voice chats such as Jitsi Meet have, would help me in this situations, so i can first check out the world without being forced to speak directly.

Joining a personal space first (like some "Home") would also help to get comfortable with the software without having to interact with other people. You could invite people later to hang out there.

There might be other resources and best practices to create a safe and welcoming onboarding for such social tools. You should coordinate with other efforts like Matrix, the VRChat Community and maybe mental health groups.

Check out these videos about your potential audience:

- https://www.youtube.com/watch?v=4PHT-zBxKQQ
- https://www.youtube.com/watch?v=5v_Dl7i4Bcw

**Screenshots**

**A scary situation**

![Screenshot from 2022-08-16 07-11-27](https://user-images.githubusercontent.com/91113/184804311-516429d4-4cee-4964-9489-ae6bd6c788f9.png)

**Desktop:**
 - OS: NixOS 22.05.2397.5c211b47aea
 - Browser: Chrome 104.0.5112.79

**Comment by robertlong** [comment]
Thanks for the request @davidak it's definitely something that's on our radar 👍
