### ISSUE TITLE
Joining via alias doesn't work on fresh thirdroom.io account

### ISSUE THREAD

**Issue by ara4n** [matrix-org/thirdroom#166]
I signed up as `@matthew:thirdroom.io` and tried to join #uk-city:thirdroom.dev, but joining via alias at https://matrix.thirdroom.io/_matrix/client/r0/join/%23uk-city%3Athirdroom.dev fails with `{"errcode":"M_UNKNOWN","error":"Failed to fetch alias"}`

**Comment by ajbura** [comment]
This now works as thirdroom.io now have federation enabled.
