### ISSUE TITLE
thirdroom.io OIDC shouldn't prompt for firstname/lastname

### ISSUE THREAD

**Issue by ara4n** [matrix-org/thirdroom#167]
we have OIDC! \o/ but it shouldn't be asking me for firstname/lastname.

also, does the email address get passed to the synapse sensibly for email notifs etc?

**Comment by hughns** [comment]
The first/last names are no longer on the registration page.

<img width="493" alt="image" src="https://user-images.githubusercontent.com/6955675/185394266-addb9fa3-806c-439c-be84-8394c46fec00.png">

However, they are still visible on the self service account management page. I can't currently find an option to hide them on there.


The email address isn't passed to the homeserver by the OP.

Like pre-OIDC the client needs to ask the HS to add an email address. The client could take the email address from the OP user info endpoint (where available) to save the user re-entering it.

Conceptually, the HS could then trust the verification status of the email address as provided by the OP.

Note that in the current thirdroom.io configuration the Keycloak isn't requiring that email addresses are verified, so this wouldn't (currently) be applicable anyhow.
