### ISSUE TITLE
504s when trying to /sync against matrix.thirdroom.io

### ISSUE THREAD

**Issue by ara4n** [matrix-org/thirdroom#169]
Syncs which hit the 30s mark seem to be timing out and failing with a 504, causing TR to do an initial sync and start over.  In practice the request seems to just stall after 30s; i think the 504 is a local timeout.

<img width="1665" alt="Screenshot 2022-08-18 at 01 47 55" src="https://user-images.githubusercontent.com/1294269/185256919-665de46d-de0d-4c73-ac29-232917024991.png">

**Comment by hughns** [comment]
There was a mismatch in the timeout settings between the OpenShift route and the Synapse haproxy.

This is now fixed.
