### ISSUE TITLE
thirdroom.io server is misnamed matrix.thirdroom.io

### ISSUE THREAD

**Issue by ara4n** [matrix-org/thirdroom#170]
The ROSA-deployed thirdroom.io has ended up printing matrix IDs of form `@matthew:matrix.thirdroom.io`, which is a major faux pas - it should be `@matthew:thirdroom.io`

**Comment by hughns** [comment]
This is in progress. However, the HS is currently down.

**Comment by hughns** [comment]
The HS name has been changed. n.b. all existing data has been cleared out.
