### ISSUE TITLE
Fix flying and jumping on boxes

### ISSUE THREAD

**Issue by robertlong** [matrix-org/thirdroom#208]

**Comment by vintprox** [comment]
**Prop flying** is a pretty common glitch that is well suited for some environments, so I wouldn't go as far as to strip it completely. Make it a room option/setting! :+1: 

(In regards to jumping, I don't know what to suggest.)

**Comment by davidak** [comment]
>I wouldn't go as far as to strip it completely

Maintaining such an option would need effort and leave less time to polish for proper physics (and other aspects), so i suggest to commit to one style of physics.

**Comment by NateTheGreatt** [comment]
this was fixed with the introduction of the new kinematic character controller provided by rapier https://github.com/matrix-org/thirdroom/pull/536

closing
