### ISSUE TITLE
Cant invite user until they've saved their profile

### ISSUE THREAD

**Issue by robertlong** [matrix-org/thirdroom#218]
**Describe the bug**
When inviting a user to a room you cant do so until they've saved their user profile. Synapse returns a NOT_FOUND error when trying to get the profile endpoint. I think we can send the invite even without this request returning.

**To Reproduce**
1. Create a new account
2. Invite that user to a room with another account
3. Observe the "User id x is invalid. Failed to invite." error message

**Expected behavior**
Inviting a user to a room should work regardless of whether or not they have saved their profile info.

**Screenshots**
![Screen Shot 2022-08-31 at 11 23 30 AM](https://user-images.githubusercontent.com/1753624/187752503-d11b0a4c-c129-4333-b43f-8eb72ff29a3f.png)

**Comment by Fi1osof** [comment]
Is this this fixed? I have this problem with last version code. And i have 404 error for current authorized user.

![image](https://user-images.githubusercontent.com/2550668/197292859-0fee153a-3588-4fe2-81e9-19f1a384e52e.png)
