### ISSUE TITLE
ThirdRoom often takes ages to launch in FF

### ISSUE THREAD

**Issue by ara4n** [matrix-org/thirdroom#235]
Copy-paste https://thirdroom.io/world/#scifi-building:thirdroom.dev into a fresh FF window.

Wait ~30s on a "Loading..." spinner until you're let into the app.

Not sure what it's doing (nothing on console).

**Comment by robertlong** [comment]
Possibly syncing your matrix account? This needs more info.

**Comment by ara4n** [comment]
I repro'd it again yesterday. There was nothing in the console. On hitting refresh it relaunched instantly :/

**Comment by robertlong** [comment]
I think this was due to not caching on room joins and some of our server infra. I'm pretty sure we're in a good state now.
