### ISSUE TITLE
Reflection probes change very abruptly

### ISSUE THREAD

**Issue by ara4n** [matrix-org/thirdroom#247]
Watching avatars running around the place, or running around the plaza on terra while holding a crate or bouncy ball, i see the ambient lighting change very abruptly. It feels like we're not lerping between the probes smoothly.

**Comment by robertlong** [comment]
Luckily this doesn't seem like a technical issue, it's just gaps in-between reflection probe bounding boxes. So it jumps to the global bounding box and then back. Also the more overlap they have the smoother the transition will be. I'll do another pass on them.

**Comment by robertlong** [comment]
Fixed in the new Terra environment
