### ISSUE TITLE
Guest access should prompt for a displayname

### ISSUE THREAD

**Issue by ara4n** [matrix-org/thirdroom#249]
So the guest has a sensible name in the app

**Comment by hughns** [comment]
This has been added to the guest OIDC Provider:

<img width="542" alt="image" src="https://user-images.githubusercontent.com/6955675/191253531-98800a4d-5626-4192-b734-e9fe565f80f2.png">

@ajbura please can you tidy up the CSS/layout?

**Comment by ajbura** [comment]
@hughns https://github.com/hughns/anon-oidc/pull/3

**Comment by hughns** [comment]
It now looks like this:

![image](https://user-images.githubusercontent.com/6955675/191570917-f432f798-eed3-4305-bb28-662dfa1a7a69.png)
