### ISSUE TITLE
Check displaynames get disambiguated correctly everywhere

### ISSUE THREAD

**Issue by ara4n** [matrix-org/thirdroom#250]
If you have two users with displayname Matthew, do they get their mxids appended to avoid confusion and impersonation attacks?

**Comment by NateTheGreatt** [comment]
currently we display the full mxid underneath the display name on the member list and tooltip views. do you think it would be prudent to also add it to the nametags?

![Image](https://user-images.githubusercontent.com/635364/193105309-ab5a3570-090e-43e3-93a8-fc24ba348c39.png)
![Image](https://user-images.githubusercontent.com/635364/193105374-5255cf5a-4352-4976-8007-3193673309a4.png)

**Comment by ajbura** [comment]
> I think the nametag is fine. The last remaining spot I can think of is the invite dialog

Fixed in https://github.com/matrix-org/thirdroom/pull/459
