### ISSUE TITLE
"Joined" section of memberlist is confusing

### ISSUE THREAD

**Issue by ara4n** [matrix-org/thirdroom#264]
"Joined" implies the users are joined to the world - rather than just present in the matrix room.  Perhaps we should say: "Connected" (for those whose m.call.member is connected) and "Disconnected" (for those who are joined to the room, but not connected to the call)?

![image](https://user-images.githubusercontent.com/1294269/190790074-37b1086b-ffc0-47fb-a41c-0f0c428057d0.png)

**Comment by robertlong** [comment]
Yeah, "Connected" and "Disconnected" makes more sense for worlds.

**Comment by robertlong** [comment]
Or "In World" and "Offline"
