### ISSUE TITLE
sometimes unable to re-establish connections when leaving and rejoining a call

### ISSUE THREAD

**Issue by NateTheGreatt** [matrix-org/thirdroom#276]
steps to reproduce:

1. establish a voice call with N peers where N > 2
2. without refreshing, disconnect and reconnect each peer from the call in a round-robin fashion
3. observe sometimes one or more peers do not reconnect to one another unless the page is fully refreshed

cc @ara4n

**Comment by bwindels** [comment]
Should be fixed in https://github.com/vector-im/hydrogen-web/commit/bb2e63b05ba568918f6e7caf56dc33e7f0b60f6f
