### ISSUE TITLE
broken homeworld selection in world list when leaving a room via `alt+L`

### ISSUE THREAD

**Issue by NateTheGreatt** [matrix-org/thirdroom#291]
1. leave any room via alt+L
2. notice homeworld is always selected after leaving any room
3. click Load World, notice nothing happens
4. select any other room, Load World now works again

**Comment by Midou36O** [comment]
I consider this a feature more than a bug :smile:

**Comment by vintprox** [comment]
> I consider this a feature more than a bug smile

Until you realize that "Load World" tries to load some non-existent world. 👀
