### ISSUE TITLE
Perfect respawn physics mean balls can bounce incredibly high & ball bounce seems to amplify with each bounce

### ISSUE THREAD

**Issue by turt2live** [matrix-org/thirdroom#302]
I guess throwing a couple objects off the map meant that they respawned in a single place, leading to a wonderfully interesting effect:

https://user-images.githubusercontent.com/1190097/191622785-887c72ee-aef4-48c1-9f58-1a25879dc34e.mp4

also, the balls seem to bounce higher and higher on their own without external force: there should be some loss from each bounce?

**Comment by NateTheGreatt** [comment]
fixed in prod - objects do not respawn after falling out of bounds now
