### ISSUE TITLE
Objects which land on your head clip inside before rolling off

### ISSUE THREAD

**Issue by turt2live** [matrix-org/thirdroom#322]
https://user-images.githubusercontent.com/1190097/191877210-41350db7-cf1e-45bb-8db5-328e269f9b24.mp4

the rolling off behaviour isn't too bad, but maybe it should "hit" a bit higher on the avatar?

**Comment by vintprox** [comment]
It may look like objects have wrong collision shape, but it's more likely that camera's positioning relative to avatar is confused or avatar's collision shape is too soft.

**Comment by NateTheGreatt** [comment]
char controller's cuboid has been adjusted to fix this
