### ISSUE TITLE
World link broken

### ISSUE THREAD

**Issue by davidak** [matrix-org/thirdroom#324]
**Describe the bug**

**To Reproduce**
1. Go to https://thirdroom.io/world/#thirdroom-public:matrix.org
2. You are redirected to https://thirdroom.io/preview

**Expected behavior**
Join the World as before.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I guess this is caused by https://github.com/matrix-org/thirdroom/pull/233.

cc @ajbura

**Comment by ajbura** [comment]
its not broken, if user is not logged in then all user are redirected to preview and if you login after that it will follow the link.

If already logged in then it will skip preview.

**Comment by davidak** [comment]
previously there was just the login, so i would expect to get to the login when i open that link and not logged in
