### ISSUE TITLE
Using Alt+L to leave world prevents loading of other worlds - requires page refresh

### ISSUE THREAD

**Issue by turt2live** [matrix-org/thirdroom#325]
1. Enter a world
2. <kbd>Alt</kbd>+<kbd>L</kbd>
3. Try to load world again (button does nothing)
4. Refresh page
5. Enter a world just fine

**Comment by NateTheGreatt** [comment]
👍 confirmed, dupe of https://github.com/matrix-org/thirdroom/issues/291
