### ISSUE TITLE
Microphone mute state not remembered between world loads

### ISSUE THREAD

**Issue by turt2live** [matrix-org/thirdroom#327]
this is a bit surprising - as far as I can tell from the MuteButton code, we don't call `setMicrophone` but also doing that doesn't magically make it work, unfortunately.

**Comment by ajbura** [comment]
It's temporary disabled https://github.com/matrix-org/thirdroom/blob/main/src/ui/views/session/SessionView.tsx#L241,L244

**Comment by ajbura** [comment]
Closing as this has been fixed in https://github.com/matrix-org/thirdroom/pull/414
