### ISSUE TITLE
Player camera set to preview camera on enter

### ISSUE THREAD

**Issue by robertlong** [matrix-org/thirdroom#335]
**Describe the bug**
I pressed enter into a room and got moved to the preview camera. Now I can't move. However I appear spawned to the other user in the room. There are no errors in the console.

**To Reproduce**
Not entirely sure. I entered the room and got kicked back to the preview camera. It seemed like it happened when the other user in the room connected.

**Screenshots**
![Screen Shot 2022-09-23 at 11 58 19 AM](https://user-images.githubusercontent.com/1753624/192038925-5e447f60-15ec-402c-a2d1-95778fc6c9b6.png)

![Screen Shot 2022-09-23 at 12 01 37 PM](https://user-images.githubusercontent.com/1753624/192038981-a244e99d-ebc2-465c-b6a3-eb77f814071f.png)

**Comment by NateTheGreatt** [comment]
this hasn't happened since our various refactor PRs so i'm going to consider this fixed and close the issue
