### ISSUE TITLE
Avatar moves on its own

### ISSUE THREAD

**Issue by turt2live** [matrix-org/thirdroom#338]
this was on terra-1 for me, on one of the platforms in the building, but I've also seen it on the floor in the homeworld:

https://user-images.githubusercontent.com/1190097/192066631-ba4f3b56-35d7-49ec-b00b-416c375319e3.mp4

No interaction from me - just sat there staring at the floor. Didn't even move the mouse.

**Comment by vintprox** [comment]
It happenns randomly for me as well.

**Comment by NateTheGreatt** [comment]
should be fixed in production now!
