### ISSUE TITLE
Default env map is upside down.

### ISSUE THREAD

**Issue by ara4n** [matrix-org/thirdroom#347]
Having applied a non-venice env map, it's apparent that normal reflecting (not reflection probe) objects like the mirrorball are showing an inverted reflection of the env map. Clouds should be on the bottom and bluesky should be on the top; not vice versa.

<img width="450" alt="Screenshot 2022-09-25 at 23 29 02" src="https://user-images.githubusercontent.com/1294269/192168453-05595c74-1f1b-41d8-bb49-3088fc6913ac.png">

**Comment by NateTheGreatt** [comment]
looks fixed now!
<img width="327" alt="image" src="https://user-images.githubusercontent.com/635364/235257560-44c377ae-e86c-4a6e-b3f2-538d84fb22c0.png">
closing
