### ISSUE TITLE
Crate Fly Glitch

### ISSUE THREAD

**Issue by davidak** [matrix-org/thirdroom#364]
**Describe the bug**

If you grab a crate that you are standing on, the crate will fly up with you.

**To Reproduce**
1. Spawn crate (press 2)
2. Jump on crate
3. Grab crate
4. Fly away

**Expected behavior**
I guess you can't move an object you stand on. In any case, don't break physics.

**Screenshots**
https://youtu.be/CLsVJ0KcR0o?t=87

**Desktop (please complete the following information):**
 - OS: NixOS Linux 22.05.3201.bcc68429a50
 - Browser: Microsoft Edge 100.0.1185.44

**Additional context**
Maybe keep this for MVP as fun easteregg for people to find out and have fun messing around, but it also kills the illusion of the world when you move too high above it.

**Comment by vintprox** [comment]
I guess it would be fun to retain as an option: Strict/Non-strict physics. That's because prop flying is such a classic, it would make more harm totally removing it than to introduce opt-in wild settings per room.

**Comment by vintprox** [comment]
Related: #208

**Comment by NateTheGreatt** [comment]
fixed as explained in #208 , closing
