### ISSUE TITLE
Climbing up on round edges

### ISSUE THREAD

**Issue by davidak** [matrix-org/thirdroom#366]
**Describe the bug**

See video. Is this a feature or a bug?

**To Reproduce**
1. Create big crate by pressing 3
2. Try to jump on crate
3. You can slowly move up

**Expected behavior**
It should be physically sane. This feels like a glitch.

**Screenshots**
https://youtu.be/CLsVJ0KcR0o?t=74

**Desktop (please complete the following information):**
OS: NixOS Linux 22.05.3201.bcc68429a50
Browser: Microsoft Edge 100.0.1185.44

**Additional context**

**Comment by NateTheGreatt** [comment]
this was fixed in the recent rapier update added in https://github.com/matrix-org/thirdroom/pull/471, closing
