### ISSUE TITLE
Clicking while the mouse is being captured prevents you from moving the camera

### ISSUE THREAD

**Issue by Midou36O** [matrix-org/thirdroom#378]
**Describe the bug**
When clicking (say throwing an object) the camera stops responding to movement of the mouse, requiring to (esc)ape and get the mouse captured again.

**To Reproduce**
1. Open any world
2. Create a box or a sphere
3. Grab the box or sphere by either clicking (Where the bug starts) or Pressing E
4. Throw the box or sphere by clicking and notice the camera stops working

**Expected behavior**
Camera should be able to move freely even after clicking.

**Screenshots**
ThirdRoom itself is too power hungry so if i record it i defenitely will get worse performance :(

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Ungoogled Chromium/ Chromium / Chrome
 - Version: The one currently running in thirdroom.io at the time this bug have been reported.

**Additional context**
N/A

**Comment by NateTheGreatt** [comment]
unable to reproduce this one. still happening for you @Midou36O ?

**Comment by Midou36O** [comment]
I can't reproduce it anymore, looks like it got solved in the meantime! Closing.
