### ISSUE TITLE
Rooms with broken permissions no longer get warned about nicely

### ISSUE THREAD

**Issue by ara4n** [matrix-org/thirdroom#411]
e.g. https://thirdroom.io/world/#terra-realtime-shadows:thirdroom.io was never updated before TP1 launch to have sensible permissions.

But rather than giving a nice warning that it needs to be updated, instead we now get a generic "3d world does not exist" error.

**Comment by robertlong** [comment]
We should update the scene for this world, but IMO that is an acceptable error message because the world is not actually a world (we swapped state events).
