### ISSUE TITLE
Positional AudioEmitters use degrees instead of radians

### ISSUE THREAD

**Issue by robertlong** [matrix-org/thirdroom#412]
You can see that the default for `coneInnerAngle` is 360 degrees when it should be 2*PI https://github.com/matrix-org/thirdroom/blob/main/src/engine/audio/audio.game.ts#L586

**Comment by WMattWood** [comment]
This may be a naive question - but I assume that this change in unit of measurement will also need to be accounted for anywhere else in the code where `coneInnerAngle` is referenced, or where values derived from this variable are used - is that correct?

**Comment by NateTheGreatt** [comment]
> https://github.com/matrix-org/thirdroom/blob/6c4f55cfc40c04bd984e8839f8441e1c0e80e9d0/src/engine/resource/schema.ts#L149
> 
> The value is fixed i think.

indeed, looks like this was fixed in https://github.com/matrix-org/thirdroom/pull/471. closing 👍
