### ISSUE TITLE
[HELP REQUIRED] World not in sync

### ISSUE THREAD

**Issue by fax1ty** [matrix-org/thirdroom#418]
1. When 2 users connect to the same world, no remote users are visible.

2. The list of players in the world does not display the current real value
![image](https://user-images.githubusercontent.com/26363214/199733027-a3403d6e-660e-4020-a12e-3aa6966cab64.png)

P.S. Federation Tester [gives an error](https://github.com/matrix-org/matrix-federation-tester/issues/130)

**Comment by robertlong** [comment]
Based on your comment on the other issue. Are you using Dendrite as your homeserver?

**Comment by fax1ty** [comment]
@robertlong Yes. This is dendrite in Docker. Requests go through nginx

**Comment by NateTheGreatt** [comment]
> Just to follow up. The problems here are configuration errors in dendrite (explicitely disabled federation) and the lack of a TURN server being configured.

going to assume this means that this issue has been solved. closing
