### ISSUE TITLE
Make the back button work when you're coming from another site

### ISSUE THREAD

**Issue by robertlong** [matrix-org/thirdroom#423]
Currently it won't let you back out of Thirdroom.io which is really annoying and breaks portal navigation from other sites.

**Comment by ajbura** [comment]
Can not reproduce. This seems to be fixed after #394 or #233 .

Current behaviour: if user is already logged in it doesn't have any back history(thirdroom related) else back history is /preview > /login  > oidc > /

**Comment by ajbura** [comment]
I found the problem

> else back history is /preview > /login > oidc > /

In this case going back to `/login` will get redirected back to `/` as user is already logged in
