### ISSUE TITLE
Profile > Graphic Quality menu disappears onclick (OSX 12.5.1, Brave, Chrome, FF)

### ISSUE THREAD

**Issue by pablo-mayrgundter** [matrix-org/thirdroom#529]
When I click on the Graphics Quality menu to activate the pulldown, the whole dialog disappears:
<img width="485" alt="image" src="https://user-images.githubusercontent.com/2480879/223573054-1f026504-000e-442f-a012-eec2c133b8ef.png">

lands me back here:
<img width="467" alt="image" src="https://user-images.githubusercontent.com/2480879/223573527-f6d9c37d-259c-446b-846c-54111a53fb93.png">

**Comment by parajbs** [comment]
I have the same problem

If I focus it with the TAB key and then use the up and down arrow keys, then I can select something.

If I click on it with the mouse then problem comes up (as in the picture above) strings it away to the HOME menu.

**Comment by pablo-mayrgundter** [comment]
Thanks, nice workaround!

**Comment by pablo-mayrgundter** [comment]
Works for me, thanks!
