### ISSUE TITLE
If you jump too high you fly out of the world and can never return

### ISSUE THREAD

**Issue by ara4n** [matrix-org/thirdroom#84]
**To Reproduce**

1. Hit jump many times to go flying.  
2. Hit it too many, and suddenly you accelerate through the roof, and the world disappears, and you can never go back. It's possible you are even accelerating (or at least travelling) out into space.
3. It's like Charlie and the Great Glass Elevator, with the Vernicious Knids, but worse.

**Expected behavior**

You can't fly out of the world.  Presumably this is a combination of clip plane for the world, but also a bug where jumping suddenly gets stuck on somehow.

Chrome 102 on macOS 12

**Comment by robertlong** [comment]
This should be fixed now. You can't double jump anymore. We will add a fly mode back in shortly.
